title:   Tony Tong
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Welcome to my Data Analyst portfolio. Here, you'll find a range of projects highlighting my expertise in analyzing data. My work involves utilizing programming languages like SQL and Python, employing powerful data visualization tools like Power BI and Tableau, and applying statistical models to interpret complex data. My aim is to use these skills to better understand and address business issues. Stay and browse through my projects to see how data analysis can provide deeper insights into your company.
  <br> <br>
  <a href="https://www.linkedin.com/in/tony-tong-291b53131/">View My LinkedIn Profile</a>
  <br>
  <a href="https://public.tableau.com/app/profile/tony.tong2493/vizzes">View My Tableau Work Samples</a>
  <br>
  <a href="https://www.notion.so/tonykachuntong/Tony-Tong-s-BI-Portfolio-667428fd80394bf9b271eaf80411c799">View My Notion Portfolios</a>
theme: jekyll-theme-minimal   
  
 
